language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'node' # use latest stable nodejs version
script:
  - npm test  # test build to build and run ava tests
  - npm run coverage  # generate nyc report
after_success:
  - npm run semantic-release
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
